// src/App.tsx
import { useEffect, useRef, useCallback } from 'react'

const App = () => {
  const textbox = useRef<HTMLInputElement>()

  const countRef = useCallback((element: HTMLInputElement) => {
    if (element) element.value = '5'
    textbox.current = element
  }, [])

  const onCreate = () => {
    const count = parseInt(textbox.current?.value || '', 10)
    parent.postMessage(
      { pluginMessage: { type: 'create-rectangles', count } },
      '*'
    )
  }

  const onCancel = () => {
    parent.postMessage({ pluginMessage: { type: 'cancel' } }, '*')
  }

  useEffect(() => {
    // This is how we read messages sent from the plugin controller
    window.onmessage = (event) => {
      const { type, message } = event.data.pluginMessage
      if (type === 'create-rectangles') {
        console.log(`Figma Says: ${message}`)
      }
    }
  }, [])

  return (
    <div>
      <h2>Rectangle Creator</h2>
      <p>
        Count: <input ref={countRef} />
      </p>
      <button id="create" onClick={onCreate}>
        Create
      </button>
      <button onClick={onCancel}>Cancel</button>
    </div>
  )
}

export default App

// src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
const count = ref(5)
const create = () => {
  parent.postMessage({ pluginMessage: { type: 'create-rectangles', count: count.value } }, '*')
}
const cancel = () => {
  parent.postMessage({ pluginMessage: { type: 'cancel' } }, '*')
}
</script>

<template>
  <h2>Rectangle Creator</h2>
  <p>Count: <input v-model="count" /></p>
  <button @click="create">Create</button>
  <button @click="cancel">Cancel</button>
</template>
